package com.ibm.cicsdev.bean;
import com.ibm.jzos.fields.*;
import java.math.*;

// Generated by IBM Record Generator for Java V3.0.2 Build 20221206-1121 on: Fri May 30 11:48:21 BST 2025

public class CommareaWrapper {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 01   DFHCOMMAREA. </pre> */
	public static final int DFHCOMMAREA_len = 104; 

	/** <pre>
	     03  DATA-PAYLOAD. </pre> */
	public static final int DATA_PAYLOAD_len = 104; 
	public static final int DATA_PAYLOAD_offset = factory.getOffset();

	/** <pre>
	        05 BINARY-DIGIT            PIC 9(4)       COMP. </pre> */
	protected static final BinaryAsIntField BINARY_DIGIT = factory.getBinaryAsIntField(4, false);

	/** <pre>
	        05 CHARACTER-STRING        PIC X(30). </pre> */
	protected static final StringField CHARACTER_STRING = factory.getStringField(30);

	/** <pre>
	        05 NUMERIC-STRING          PIC 9(18). </pre> */
	protected static final ExternalDecimalAsLongField NUMERIC_STRING = factory.getExternalDecimalAsLongField(18, false, false, false, false);

	/** <pre>
	        05 PACKED-DIGIT            PIC 9(15)      COMP-3. </pre> */
	protected static final PackedDecimalAsLongField PACKED_DIGIT = factory.getPackedDecimalAsLongField(15, false);

	/** <pre>
	        05 PACKED-DIGIT-WITH-COMMA PIC 9(12)V9(3) COMP-3. </pre> */
	protected static final PackedDecimalAsBigDecimalField PACKED_DIGIT_WITH_COMMA = factory.getPackedDecimalAsBigDecimalField(15, 3, false);

	/** <pre>
	        05 SIGNED-PACKED           PIC S9(12)     COMP-3. </pre> */
	protected static final PackedDecimalAsLongField SIGNED_PACKED = factory.getPackedDecimalAsLongField(12, true);

	/** <pre>
	        05 BOOL                    PIC X. </pre> */
	protected static final StringField BOOL = factory.getStringField(1);

	/** <pre>
	           88 BOOL-FALSE           value X'00'. </pre> */
	/** NOTE: this constant value form is not supported */

	/** <pre>
	           88 BOOL-TRUE            value X'01' through X'FF'. </pre> */
	/** NOTE: this constant value form is not supported */

	/** <pre>
	        05 RESULT. </pre> */
	public static final int RESULT_len = 30; 
	public static final int RESULT_offset = factory.getOffset();

	/** <pre>
	           09 RESULT-CODE          PIC S9(5)      VALUE +0. </pre> */
	protected static final ExternalDecimalAsIntField RESULT_CODE = factory.getExternalDecimalAsIntField(5, true, true, false, false);

	/** <pre>
	           09 RESULT-TEXT          PIC X(25). </pre> */
	protected static final StringField RESULT_TEXT = factory.getStringField(25);

	protected byte[] _byteBuffer;
	// Instance variables used to cache field values
	protected int binaryDigit;
	protected boolean binaryDigitIsSet;
	protected String characterString;
	protected long numericString;
	protected boolean numericStringIsSet;
	protected long packedDigit;
	protected boolean packedDigitIsSet;
	protected BigDecimal packedDigitWithComma;
	protected long signedPacked;
	protected boolean signedPackedIsSet;
	protected String bool;
	protected int resultCode;
	protected boolean resultCodeIsSet;
	protected String resultText;


	public CommareaWrapper (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public CommareaWrapper () {
		this._byteBuffer = new byte[DFHCOMMAREA_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public int getBinaryDigit() {
		if (!binaryDigitIsSet) {
			binaryDigit = BINARY_DIGIT.getInt(_byteBuffer);
			binaryDigitIsSet = true;
		}
		return binaryDigit;
	}

	public void setBinaryDigit(int binaryDigit) {
		if (binaryDigitIsSet && BINARY_DIGIT.equals(this.binaryDigit, binaryDigit)) {
			return;
		}
		BINARY_DIGIT.putInt(binaryDigit, _byteBuffer);
		this.binaryDigit = binaryDigit;
		binaryDigitIsSet = true;
	}

	public String getCharacterString() {
		if (characterString == null) {
			characterString = CHARACTER_STRING.getString(_byteBuffer);
		}
		return characterString;
	}

	public void setCharacterString(String characterString) {
		if (CHARACTER_STRING.equals(this.characterString, characterString)) {
			return;
		}
		CHARACTER_STRING.putString(characterString, _byteBuffer);
		this.characterString = characterString;
	}

	public long getNumericString() {
		if (!numericStringIsSet) {
			numericString = NUMERIC_STRING.getLong(_byteBuffer);
			numericStringIsSet = true;
		}
		return numericString;
	}

	public void setNumericString(long numericString) {
		if (numericStringIsSet && NUMERIC_STRING.equals(this.numericString, numericString)) {
			return;
		}
		NUMERIC_STRING.putLong(numericString, _byteBuffer);
		this.numericString = numericString;
		numericStringIsSet = true;
	}

	public long getPackedDigit() {
		if (!packedDigitIsSet) {
			packedDigit = PACKED_DIGIT.getLong(_byteBuffer);
			packedDigitIsSet = true;
		}
		return packedDigit;
	}

	public void setPackedDigit(long packedDigit) {
		if (packedDigitIsSet && PACKED_DIGIT.equals(this.packedDigit, packedDigit)) {
			return;
		}
		PACKED_DIGIT.putLong(packedDigit, _byteBuffer);
		this.packedDigit = packedDigit;
		packedDigitIsSet = true;
	}

	public BigDecimal getPackedDigitWithComma() {
		if (packedDigitWithComma == null) {
			packedDigitWithComma = PACKED_DIGIT_WITH_COMMA.getBigDecimal(_byteBuffer);
		}
		return packedDigitWithComma;
	}

	public void setPackedDigitWithComma(BigDecimal packedDigitWithComma) {
		if (PACKED_DIGIT_WITH_COMMA.equals(this.packedDigitWithComma, packedDigitWithComma)) {
			return;
		}
		PACKED_DIGIT_WITH_COMMA.putBigDecimal(packedDigitWithComma, _byteBuffer);
		this.packedDigitWithComma = packedDigitWithComma;
	}

	public long getSignedPacked() {
		if (!signedPackedIsSet) {
			signedPacked = SIGNED_PACKED.getLong(_byteBuffer);
			signedPackedIsSet = true;
		}
		return signedPacked;
	}

	public void setSignedPacked(long signedPacked) {
		if (signedPackedIsSet && SIGNED_PACKED.equals(this.signedPacked, signedPacked)) {
			return;
		}
		SIGNED_PACKED.putLong(signedPacked, _byteBuffer);
		this.signedPacked = signedPacked;
		signedPackedIsSet = true;
	}

	public String getBool() {
		if (bool == null) {
			bool = BOOL.getString(_byteBuffer);
		}
		return bool;
	}

	public void setBool(String bool) {
		if (BOOL.equals(this.bool, bool)) {
			return;
		}
		BOOL.putString(bool, _byteBuffer);
		this.bool = bool;
	}

	public int getResultCode() {
		if (!resultCodeIsSet) {
			resultCode = RESULT_CODE.getInt(_byteBuffer);
			resultCodeIsSet = true;
		}
		return resultCode;
	}

	public void setResultCode(int resultCode) {
		if (resultCodeIsSet && RESULT_CODE.equals(this.resultCode, resultCode)) {
			return;
		}
		RESULT_CODE.putInt(resultCode, _byteBuffer);
		this.resultCode = resultCode;
		resultCodeIsSet = true;
	}

	public String getResultText() {
		if (resultText == null) {
			resultText = RESULT_TEXT.getString(_byteBuffer);
		}
		return resultText;
	}

	public void setResultText(String resultText) {
		if (RESULT_TEXT.equals(this.resultText, resultText)) {
			return;
		}
		RESULT_TEXT.putString(resultText, _byteBuffer);
		this.resultText = resultText;
	}

}
